name: Auto Telegram Post

on:
  schedule:
    # গিটহাব UTC টাইম মেনে চলে। বাংলাদেশ সময় সকাল ১০টা মানে UTC 04:00 এবং রাত ৮টা মানে UTC 14:00
    - cron: '0 4,14 * * *'
  workflow_dispatch: # এই লাইনের কারণে আপনি চাইলে ম্যানুয়ালিও রান করতে পারবেন

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Python Script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        run: python main.py
